name: build #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - master
jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@master #软件市场的名称
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.11
        with:
          hugo-version: '0.66.0'
          extended: true

      - name: Build
        run: hugo --gc --minify --buildFuture --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: yuhixyz/yuhixyz.github.io
          publish_branch: build
          publish_dir: ./public
          allow_empty_commit: true