name: build

on:
  push:
    branches:
      - master # push到master分支时触发

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.72.0'
          extended: true

      - name: Build # hugo生成public
        run: |
          git config --global core.quotepath false         
          hugo --gc --minify --cleanDestinationDir
      
      - name: Node.js # npm
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Algolia # algolia搜索
        run: |
          npm install hugo-algolia -g
          hugo-algolia -s
        env:
          ALGOLIA_WRITE_KEY: ${{ secrets.ALGOLIA_WRITE_KEY }} # adminkey

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          force_orphan: true

      - name: Deploy_Aliyun
        uses: easingthemes/ssh-deploy@v2.0.7
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_ACCESS_TOKEN }}
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.ALIYUN_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.ALIYUN_REMOTE_USER }}
          TARGET: ${{ secrets.ALIYUN_TARGET }}
