name: build

on:
  push:
    branches:
      - master  # push 到 master 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo  # 安装 hugo-extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.72.0'
          extended: true

      - name: Node.js  # 安装 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Packages  # 安装各种依赖
        run: |
          npm install hugo-algolia -g
          npm install workbox-build gulp gulp-uglify readable-stream uglify-es --save-dev

      - name: Build # hugo生成public
        run: |
          git config --global core.quotepath false         
          hugo --gc --minify --cleanDestinationDir
          gulp build
          hugo-algolia -s
        env:
          ALGOLIA_WRITE_KEY: ${{ secrets.ALGOLIA_WRITE_KEY }}  # algolia adminkey

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          cname: yuhi.xyz 
          force_orphan: true
 
      # - name: SSH to Tencent Lighthouse & pull code from github
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.TENCENT_HOST }}
      #     username: ${{ secrets.TENCENT_USERNAME }}
      #     key: ${{ secrets.TENCENT_KEY }}
      #     port: ${{ secrets.TENCENT_PORT }}
      #     timeout: 10m
      #     command_timeout: 10m
      #     script_stop: true
      #     script: |
      #       cd /www/wwwroot
      #       sudo rm -rf yuhi.xyz
      #       git clone -b build https://github.com.cnpmjs.org/yuhixyz/yuhixyz.github.io.git yuhi.xyz
            
